# permissions for end users to edit depscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: depscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: depscaler-editor-role
rules:
- apiGroups:
  - depscale.yrs.scaler
  resources:
  - depscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - depscale.yrs.scaler
  resources:
  - depscalers/status
  verbs:
  - get
